import { useMemo, useState, useEffect } from 'react'
import { Link } from 'react-router'
import { ArrowLeft, Heart, MapPin, Search, SlidersHorizontal, Star, Trash2 } from 'lucide-react'
import { Header } from '../App'
import { getFavorites, removeFavorite } from '../services/favorites'
import type { FavoriteItem } from '../types'

const sortOptions = [{ id: 'recent', label: 'الأحدث حفظًا' }, { id: 'low', label: 'السعر: الأقل أولاً' }, { id: 'high', label: 'السعر: الأعلى أولاً' }]
const price = (value: string) => Number(value.replace(/[^0-9٠-٩]/g, '').replace(/[٠-٩]/g, d => String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)))) || 0

export default function Favorites() {
  const [items, setItems] = useState<FavoriteItem[]>([]); useEffect(() => { getFavorites().then(setItems).catch(() => {}) }, []); const [sort, setSort] = useState('recent'); const [query, setQuery] = useState('')
  const visible = useMemo(() => items.filter(item => item.name.includes(query) || item.category.includes(query)).sort((a, b) => sort === 'recent' ? +new Date(b.savedAt) - +new Date(a.savedAt) : sort === 'low' ? price(a.price) - price(b.price) : price(b.price) - price(a.price)), [items, query, sort])
  const remove = async (id: string) => { try { await removeFavorite(id); setItems(prev => prev.filter(item => item.id !== id)) } catch (e) { console.error(e) } }
  return <div dir="rtl" lang="ar" className="min-h-screen bg-cream"><Header /><main className="mx-auto max-w-6xl px-5 py-8 sm:py-11"><section className="relative overflow-hidden rounded-[2rem] bg-brand px-6 py-9 text-cream sm:px-10"><div className="absolute -left-10 -top-16 h-48 w-48 rounded-full bg-amber/15" /><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black tracking-[.14em] text-amber">قائمة الأشياء التي لفتت انتباهك</p><h1 className="editorial-display mt-2 text-5xl leading-none">المفضلة</h1><p className="mt-4 max-w-xl text-sm leading-7 text-cream/75">احفظ ما قد تحتاجه لاحقًا، ثم ارجع إليه وقتما تشاء.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-5 py-4"><p className="text-xs text-cream/65">عناصر محفوظة</p><p className="mt-1 text-3xl font-black">{items.length}</p></div></div></section><div className="mt-7 flex flex-col gap-4 border-b border-line pb-5 lg:flex-row lg:items-center lg:justify-between"><label className="flex h-11 items-center gap-2 rounded-xl border border-line bg-white px-3 text-ink/50 lg:w-72"><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث في المفضلة" className="min-w-0 flex-1 bg-transparent text-sm text-ink outline-none placeholder:text-ink/40" /></label><div className="flex items-center gap-2"><SlidersHorizontal size={17} className="text-brand" /><select value={sort} onChange={event => setSort(event.target.value)} className="rounded-xl border border-line bg-white px-3 py-2.5 text-sm font-bold text-ink outline-none focus:border-brand">{sortOptions.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select></div></div>{visible.length ? <div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map(item => <FavoriteCard key={item.id} item={item} onRemove={() => remove(item.id)} />)}</div> : <EmptyFavorites query={query} />}</main></div>
}

function FavoriteCard({ item, onRemove }: { item: FavoriteItem; onRemove: () => void }) { return <article className="group overflow-hidden rounded-[1.6rem] border border-line bg-white transition hover:-translate-y-1 hover:shadow-[0_22px_44px_-32px_rgba(7,92,61,.24)]"><div className="relative aspect-[4/3] overflow-hidden bg-brand-soft"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><button onClick={onRemove} aria-label={`إزالة ${item.name} من المفضلة`} className="absolute left-3 top-3 grid h-10 w-10 place-items-center rounded-full bg-white/95 text-rose shadow-sm transition hover:bg-rose hover:text-white"><Heart size={18} fill="currentColor" /></button></div><div className="p-5"><p className="text-xs font-bold text-brand">{item.category}</p><Link to={`/listing/${item.id}`} className="mt-2 block text-lg font-black text-ink hover:text-brand">{item.name}</Link><p className="mt-2 text-xl font-black text-amber">{item.price} <span className="text-xs text-ink/55">ر.س / يوم</span></p><div className="mt-4 flex items-center justify-between border-t border-line pt-4 text-xs"><span className="inline-flex items-center gap-1.5 text-ink/60"><MapPin size={14} className="text-brand" /> {item.city}</span><span className="inline-flex items-center gap-1 font-bold text-ink/75"><Star size={14} fill="currentColor" className="text-amber" /> {item.rating}</span></div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-ink/50">مقدّم من {item.owner}</span><Link to={`/listing/${item.id}`} className="inline-flex items-center gap-1 text-sm font-black text-brand hover:underline">عرض الإعلان <ArrowLeft size={15} /></Link></div></div></article> }
function EmptyFavorites({ query }: { query: string }) { return <div className="mt-7 rounded-[1.8rem] border border-dashed border-line bg-white px-6 py-20 text-center"><Heart className="mx-auto text-rose" size={39} /><h2 className="mt-5 text-2xl font-black text-ink">{query ? 'لا توجد عناصر مطابقة' : 'قائمة المفضلة ما زالت فارغة'}</h2><p className="mt-2 text-sm leading-6 text-ink/55">{query ? 'جرّب عبارة بحث أخرى.' : 'اضغط على رمز القلب في أي إعلان لتجده هنا لاحقًا.'}</p><Link to="/search" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-black text-cream">تصفّح الإعلانات <ArrowLeft size={17} /></Link></div> }
