import { useState, useEffect } from 'react'
import { Link, useNavigate } from 'react-router'
import { ArrowLeft, Clock3, Edit3, MapPin, Play, Search, SlidersHorizontal, Trash2, X } from 'lucide-react'
import { Header } from '../App'
import { getSavedSearches, deleteSavedSearch, updateSavedSearch } from '../services/savedSearches'
import type { SavedSearch } from '../types'

const priceLabels: Record<string, string> = { any: 'كل الأسعار', 'under-150': 'أقل من ١٥٠', '150-250': 'من ١٥٠ إلى ٢٥٠', 'over-250': 'أكثر من ٢٥٠' }

export default function SavedSearches() {
  const navigate = useNavigate(); const [items, setItems] = useState<SavedSearch[]>([]); useEffect(() => { getSavedSearches().then(setItems).catch(() => {}) }, []); const [editing, setEditing] = useState<SavedSearch | null>(null); const [notice, setNotice] = useState('')
  const remove = async (id: string) => { try { await deleteSavedSearch(id); setItems(prev => prev.filter(item => item.id !== id)); setNotice('تم حذف البحث المحفوظ.'); window.setTimeout(() => setNotice(''), 2300) } catch(e) { console.error(e) } }
  const run = (item: SavedSearch) => { const params = new URLSearchParams({ q: item.query, price: item.priceRange, rating: String(item.minimumRating), location: item.location, latest: item.latestOnly ? '1' : '0' }); navigate(`/search?${params.toString()}`) }
  const update = async (name: string) => { if (!editing) return; try { await updateSavedSearch(editing.id, name); setItems(prev => prev.map(item => item.id === editing.id ? { ...item, name } : item)); setEditing(null); setNotice('تم تعديل اسم البحث.'); window.setTimeout(() => setNotice(''), 2300) } catch(e) { console.error(e) } }
  return <div dir="rtl" lang="ar" className="min-h-screen bg-cream"><Header /><main className="mx-auto max-w-5xl px-5 py-8 sm:py-11"><div className="flex flex-wrap items-end justify-between gap-5 border-b border-line pb-8"><div><p className="text-xs font-black tracking-[.14em] text-amber">ارجع إلى ما يهمك بسرعة</p><h1 className="editorial-display mt-2 text-5xl leading-none text-ink">عمليات البحث المحفوظة</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-ink/60">احفظ معايير بحثك المفضلة ثم شغّلها من هنا في أي وقت.</p></div><Link to="/search" className="inline-flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-black text-cream hover:bg-[#064b32]"><Search size={17} /> بحث جديد</Link></div>{notice && <p className="mt-5 rounded-xl bg-green/10 px-4 py-3 text-sm font-bold text-green">{notice}</p>}<div className="mt-7 grid gap-4">{items.length ? items.map(item => <SearchCard key={item.id} item={item} onRun={() => run(item)} onEdit={() => setEditing(item)} onDelete={() => remove(item.id)} />) : <EmptyState />}</div></main>{editing && <RenameModal item={editing} onClose={() => setEditing(null)} onSave={update} />}</div>
}

function SearchCard({ item, onRun, onEdit, onDelete }: { item: SavedSearch; onRun: () => void; onEdit: () => void; onDelete: () => void }) { const filters = [item.query && `“${item.query}”`, item.location !== 'كل المدن' && item.location, item.priceRange !== 'any' && priceLabels[item.priceRange], item.minimumRating > 0 && `${item.minimumRating}+ تقييم`, item.latestOnly && 'الأحدث أولًا'].filter(Boolean); return <article className="grid gap-5 rounded-[1.6rem] border border-line bg-white p-5 transition hover:border-brand/35 hover:shadow-[0_18px_42px_-30px_rgba(7,92,61,.24)] sm:grid-cols-[auto_1fr_auto] sm:items-center"><div className="grid h-13 w-13 place-items-center rounded-2xl bg-brand-soft text-brand"><SlidersHorizontal size={22} /></div><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-black text-ink">{item.name}</h2><span className="inline-flex items-center gap-1 text-xs text-ink/45"><Clock3 size={13} /> محفوظ مؤخرًا</span></div><div className="mt-3 flex flex-wrap gap-2">{filters.map(filter => <span key={String(filter)} className="rounded-full bg-cream px-3 py-1.5 text-xs font-bold text-ink/65">{filter}</span>)}</div></div><div className="flex flex-wrap gap-2 sm:justify-end"><button onClick={onRun} className="inline-flex items-center gap-1.5 rounded-xl bg-brand px-4 py-2.5 text-sm font-black text-cream hover:bg-[#064b32]"><Play size={15} fill="currentColor" /> تشغيل البحث</button><button onClick={onEdit} className="grid h-10 w-10 place-items-center rounded-xl border border-line text-brand hover:bg-brand-soft" aria-label="تعديل الاسم"><Edit3 size={16} /></button><button onClick={onDelete} className="grid h-10 w-10 place-items-center rounded-xl border border-rose/20 text-rose hover:bg-rose/10" aria-label="حذف البحث"><Trash2 size={16} /></button></div></article> }
function RenameModal({ item, onClose, onSave }: { item: SavedSearch; onClose: () => void; onSave: (name: string) => void }) { const [name, setName] = useState(item.name); return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/45 p-5"><form onSubmit={event => { event.preventDefault(); if (name.trim()) onSave(name.trim()) }} className="w-full max-w-md rounded-[1.7rem] bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-[.12em] text-brand">تعديل البحث</p><h2 className="mt-1 text-2xl font-black text-ink">سمِّ هذا البحث</h2></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full hover:bg-brand-soft"><X size={19} /></button></div><label className="mt-6 block text-sm font-bold text-ink">اسم البحث<input autoFocus value={name} onChange={event => setName(event.target.value)} className="mt-2 w-full rounded-xl border border-line px-4 py-3 text-sm font-normal outline-none focus:border-brand focus:ring-2 focus:ring-brand/10" /></label><button className="mt-6 w-full rounded-xl bg-brand py-3.5 text-sm font-black text-cream">حفظ الاسم</button></form></div> }
function EmptyState() { return <div className="rounded-[1.8rem] border border-dashed border-line bg-white px-6 py-20 text-center"><Search className="mx-auto text-brand" size={38} /><h2 className="mt-5 text-2xl font-black text-ink">لم تحفظ بحثًا بعد</h2><p className="mt-2 text-sm text-ink/55">اضبط الفلاتر من صفحة البحث ثم احفظها للعودة إليها لاحقًا.</p><Link to="/search" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-black text-cream">ابدأ البحث <ArrowLeft size={17} /></Link></div> }
